// AUTO-GENERATED from canonical BotC character data (bra1n/townsquare roles.json).
// Manual-board character data only (no night-action engine). Edit here directly;
// there is no live generator in the repo. See editions/types.ts for the shape.
import type { EditionRole } from './types'

export const BAD_MOON_RISING: EditionRole[] = [
  {
    id: 'grandmother', team: 'townsfolk', icon: 'user',
    firstNight: 40, otherNight: 51,
    name: 'Grandmother',
    ability: 'You start knowing a good player & their character. If the Demon kills them, you die too.',
    reminders: [{ label: 'Grandchild', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'sailor', team: 'townsfolk', icon: 'user',
    firstNight: 11, otherNight: 4,
    name: 'Sailor',
    ability: 'Each night, choose an alive player: either you or they are drunk until dusk. You can\'t die.',
    reminders: [{ label: 'Drunk', icon: 'beer', tone: 'good' }],
  },
  {
    id: 'chambermaid', team: 'townsfolk', icon: 'user',
    firstNight: 51, otherNight: 70,
    name: 'Chambermaid',
    ability: 'Each night, choose 2 alive players (not yourself): you learn how many woke tonight due to their ability.',
    reminders: [],
  },
  {
    id: 'exorcist', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 21,
    name: 'Exorcist',
    ability: 'Each night*, choose a player (different to last night): the Demon, if chosen, learns who you are then doesn\'t wake tonight.',
    reminders: [{ label: 'Chosen', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'innkeeper', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 9,
    name: 'Innkeeper',
    ability: 'Each night*, choose 2 players: they can\'t die tonight, but 1 is drunk until dusk.',
    reminders: [{ label: 'Protected', icon: 'shield', tone: 'good' }, { label: 'Drunk', icon: 'beer', tone: 'good' }],
  },
  {
    id: 'gambler', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 10,
    name: 'Gambler',
    ability: 'Each night*, choose a player & guess their character: if you guess wrong, you die.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'good' }],
  },
  {
    id: 'gossip', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 38,
    name: 'Gossip',
    ability: 'Each day, you may make a public statement. Tonight, if it was true, a player dies.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'good' }],
  },
  {
    id: 'courtier', team: 'townsfolk', icon: 'user',
    firstNight: 19, otherNight: 8,
    name: 'Courtier',
    ability: 'Once per game, at night, choose a character: they are drunk for 3 nights & 3 days.',
    reminders: [{ label: 'Drunk 3', icon: 'beer', tone: 'good' }, { label: 'Drunk 2', icon: 'beer', tone: 'good' }, { label: 'Drunk 1', icon: 'beer', tone: 'good' }, { label: 'No ability', icon: 'zapOff', tone: 'good' }],
  },
  {
    id: 'professor', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 43,
    name: 'Professor',
    ability: 'Once per game, at night*, choose a dead player: if they are a Townsfolk, they are resurrected.',
    reminders: [{ label: 'Alive', icon: 'circleDot', tone: 'good' }, { label: 'No ability', icon: 'zapOff', tone: 'good' }],
  },
  {
    id: 'minstrel', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Minstrel',
    ability: 'When a Minion dies by execution, all other players (except Travellers) are drunk until dusk tomorrow.',
    reminders: [{ label: 'Everyone drunk', icon: 'beer', tone: 'good' }],
  },
  {
    id: 'tea_lady', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Tea Lady',
    ability: 'If both your alive neighbours are good, they can\'t die.',
    reminders: [{ label: 'Can not die', icon: 'skull', tone: 'good' }],
  },
  {
    id: 'pacifist', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Pacifist',
    ability: 'Executed good players might not die.',
    reminders: [],
  },
  {
    id: 'fool', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Fool',
    ability: 'The first time you die, you don\'t.',
    reminders: [{ label: 'No ability', icon: 'zapOff', tone: 'good' }],
  },
  {
    id: 'tinker', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: 49,
    name: 'Tinker',
    ability: 'You might die at any time.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'neutral' }],
  },
  {
    id: 'moonchild', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: 50,
    name: 'Moonchild',
    ability: 'When you learn that you died, publicly choose 1 alive player. Tonight, if it was a good player, they die.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'neutral' }],
  },
  {
    id: 'goon', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Goon',
    ability: 'Each night, the 1st player to choose you with their ability is drunk until dusk. You become their alignment.',
    reminders: [{ label: 'Drunk', icon: 'beer', tone: 'neutral' }],
  },
  {
    id: 'lunatic', team: 'outsider', icon: 'userX',
    firstNight: 8, otherNight: 20,
    name: 'Lunatic',
    ability: 'You think you are a Demon, but you are not. The Demon knows who you are & who you choose at night.',
    reminders: [{ label: 'Attack 1', icon: 'circleDot', tone: 'neutral' }, { label: 'Attack 2', icon: 'circleDot', tone: 'neutral' }, { label: 'Attack 3', icon: 'circleDot', tone: 'neutral' }],
  },
  {
    id: 'godfather', team: 'minion', icon: 'swords',
    firstNight: 21, otherNight: 37, setup: true,
    name: 'Godfather',
    ability: 'You start knowing which Outsiders are in play. If 1 died today, choose a player tonight: they die. [−1 or +1 Outsider]',
    reminders: [{ label: 'Died today', icon: 'skull', tone: 'evil' }, { label: 'Dead', icon: 'skull', tone: 'evil' }],
  },
  {
    id: 'devils_advocate', team: 'minion', icon: 'swords',
    firstNight: 22, otherNight: 13,
    name: 'Devil\'s Advocate',
    ability: 'Each night, choose a living player (different to last night): if executed tomorrow, they don\'t die.',
    reminders: [{ label: 'Survives execution', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'assassin', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: 36,
    name: 'Assassin',
    ability: 'Once per game, at night*, choose a player: they die, even if for some reason they could not.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'evil' }, { label: 'No ability', icon: 'zapOff', tone: 'evil' }],
  },
  {
    id: 'mastermind', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: null,
    name: 'Mastermind',
    ability: 'If the Demon dies by execution (ending the game), play for 1 more day. If a player is then executed, their team loses.',
    reminders: [],
  },
  {
    id: 'zombuul', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 25,
    name: 'Zombuul',
    ability: 'Each night*, if no-one died today, choose a player: they die. The 1st time you die, you live but register as dead.',
    reminders: [{ label: 'Died today', icon: 'skull', tone: 'evil' }, { label: 'Dead', icon: 'skull', tone: 'evil' }],
  },
  {
    id: 'pukka', team: 'demon', icon: 'flame',
    firstNight: 28, otherNight: 26,
    name: 'Pukka',
    ability: 'Each night, choose a player: they are poisoned. The previously poisoned player dies then becomes healthy.',
    reminders: [{ label: 'Poisoned', icon: 'flask', tone: 'evil' }, { label: 'Dead', icon: 'skull', tone: 'evil' }],
  },
  {
    id: 'shabaloth', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 27,
    name: 'Shabaloth',
    ability: 'Each night*, choose 2 players: they die. A dead player you chose last night might be regurgitated.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'evil' }, { label: 'Alive', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'po', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 28,
    name: 'Po',
    ability: 'Each night*, you may choose a player: they die. If your last choice was no-one, choose 3 players tonight.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'evil' }, { label: '3 attacks', icon: 'circleDot', tone: 'evil' }],
  },
]
