// AUTO-GENERATED from canonical BotC character data (bra1n/townsquare +
// botc.online big-json, merged). Covers every official character NOT already
// hand-authored in the app (Experimental, Fabled, Travellers) — TB lives in
// roles/definition, Sects & Violets + Bad Moon Rising in editions/. Data-only
// (manual board; storyteller runs abilities by hand). Regenerate by re-merging
// the canonical sources; do not hand-edit rows. firstNight/otherNight are
// canonical night-order positions (null = does not act that night).
//
// HAND-AUTHORED (no canonical data feed yet — newest characters): deus_ex_fiasco,
// ferryman, hermit, princess, steward, wraith. Verified against the official wiki
// (team + ability). Preserve these rows if regenerating from the data sources.
import type { EditionRole } from './types'

export const CATALOG_CHARACTERS: EditionRole[] = [
  {
    id: 'al_hadikhia', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 33,
    name: 'Al-Hadikhia',
    ability: 'Each night*, choose 3 players (all players learn who): each silently chooses to live or die, but if all live, all die.',
    reminders: [{ label: '1', icon: 'circleDot', tone: 'evil' }, { label: '2', icon: 'circleDot', tone: 'evil' }, { label: '3', icon: 'circleDot', tone: 'evil' }, { label: 'Chose death', icon: 'circleDot', tone: 'evil' }, { label: 'Chose life', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'kazali', team: 'demon', icon: 'flame',
    firstNight: 1, otherNight: 24, setup: true,
    name: 'Kazali',
    ability: 'Each night*, choose a player: they die. [You choose which players are which Minions. -? to +? Outsiders]',
    reminders: [{ label: 'Dead', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'legion', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 23, setup: true,
    name: 'Legion',
    ability: 'Each night*, a player might die. Executions fail if only evil voted. You register as a Minion too. [Most players are Legion]',
    reminders: [{ label: 'Dead', icon: 'circleDot', tone: 'evil' }, { label: 'About to die', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'leviathan', team: 'demon', icon: 'flame',
    firstNight: 54, otherNight: 73,
    name: 'Leviathan',
    ability: 'If more than 1 good player is executed, you win. All players know you are in play. After day 5, evil wins.',
    reminders: [{ label: 'Day 1', icon: 'circleDot', tone: 'evil' }, { label: 'Day 2', icon: 'circleDot', tone: 'evil' }, { label: 'Day 3', icon: 'circleDot', tone: 'evil' }, { label: 'Day 4', icon: 'circleDot', tone: 'evil' }, { label: 'Day 5', icon: 'circleDot', tone: 'evil' }, { label: 'Good player executed', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'lil_monsta', team: 'demon', icon: 'flame',
    firstNight: 15, otherNight: 35, setup: true,
    name: 'Lil\' Monsta',
    ability: 'Each night, Minions choose who babysits Lil\' Monsta\'s token & "is the Demon". A player dies each night*. [+1 Minion]',
    reminders: [{ label: 'Is the Demon', icon: 'circleDot', tone: 'evil' }, { label: 'Dead', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'lleech', team: 'demon', icon: 'flame',
    firstNight: 16, otherNight: 34,
    name: 'Lleech',
    ability: 'Each night*, choose a player: they die. You start by choosing an alive player: they are poisoned - you die if & only if they die.',
    reminders: [{ label: 'Dead', icon: 'circleDot', tone: 'evil' }, { label: 'Poisoned', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'lord_of_typhon', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 24, setup: true,
    name: 'Lord of Typhon',
    ability: 'Each night*, choose a player: they die. [Evil characters are in a line. You are in the middle. +1 Minion. -? to +? Outsiders]',
    reminders: [{ label: 'Dead', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'ojo', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 24,
    name: 'Ojo',
    ability: 'Each night*, choose a character: they die. If they are not in play, the Storyteller chooses who dies.',
    reminders: [{ label: 'Dead', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'riot', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: null, setup: true,
    name: 'Riot',
    ability: 'Nominees die, but may nominate again immediately (on day 3, they must). After day 3, evil wins. [All Minions are Riot]',
    reminders: [],
  },
  {
    id: 'yaggababble', team: 'demon', icon: 'flame',
    firstNight: 5, otherNight: 36,
    name: 'Yaggababble',
    ability: 'You start knowing a secret phrase. For each time you said it publicly today, a player might die.',
    reminders: [{ label: 'Babbled', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'angel', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Angel',
    ability: 'Something bad might happen to whoever is most responsible for the death of a new player.',
    reminders: [{ label: 'Protect', icon: 'circleDot', tone: 'good' }, { label: 'Something Bad', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'buddhist', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Buddhist',
    ability: 'For the first 2 minutes of each day, veteran players may not talk.',
    reminders: [],
  },
  {
    id: 'deus_ex_fiasco', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Deus ex Fiasco',
    ability: 'At any time, you may deliberately break the rules, then correct it. Afterwards, declare that you have made a mistake, and add the Whoopsie reminder.',
    reminders: [{ label: 'Whoopsie', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'djinn', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Djinn',
    ability: 'Use the Djinn\'s special rule. All players know what it is.',
    reminders: [],
  },
  {
    id: 'doomsayer', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Doomsayer',
    ability: 'If 4 or more players live, each living player may publicly choose (once per game) that a player of their own alignment dies.',
    reminders: [],
  },
  {
    id: 'duchess', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: 1,
    name: 'Duchess',
    ability: 'Each day, 3 players may choose to visit you. At night*, each visitor learns how many visitors are evil, but 1 gets false info.',
    reminders: [{ label: 'Visitor', icon: 'circleDot', tone: 'good' }, { label: 'False Info', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'fibbin', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Fibbin',
    ability: 'Once per game, 1 good player might get false information.',
    reminders: [{ label: 'Used', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'fiddler', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Fiddler',
    ability: 'Once per game, the Demon secretly chooses an opposing player: all players choose which of these 2 players win.',
    reminders: [],
  },
  {
    id: 'hells_librarian', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Hell\'s Librarian',
    ability: 'Something bad might happen to whoever talks when the Storyteller has asked for silence.',
    reminders: [{ label: 'Something Bad', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'revolutionary', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Revolutionary',
    ability: '2 neighboring players are known to be the same alignment. Once per game, one of them registers falsely.',
    reminders: [{ label: 'Used', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'sentinel', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null, setup: true,
    name: 'Sentinel',
    ability: 'There might be 1 extra or 1 fewer Outsider in play.',
    reminders: [],
  },
  {
    id: 'spirit_of_ivory', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Spirit of Ivory',
    ability: 'There can\'t be more than 1 extra evil player.',
    reminders: [{ label: 'No extra evil', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'toymaker', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: 1,
    name: 'Toymaker',
    ability: 'The Demon may choose not to attack & must do this at least once per game. Evil players get normal starting info.',
    reminders: [{ label: 'Final Night: No Attack', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'boffin', team: 'minion', icon: 'swords',
    firstNight: 1, otherNight: null, setup: true,
    name: 'Boffin',
    ability: 'The Demon (even if drunk or poisoned) has a not-in-play good character\'s ability. You both know which.',
    reminders: [],
  },
  {
    id: 'boomdandy', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: null,
    name: 'Boomdandy',
    ability: 'If you are executed, all but 3 players die. 1 minute later, the player with the most players pointing at them dies.',
    reminders: [],
  },
  {
    id: 'fearmonger', team: 'minion', icon: 'swords',
    firstNight: 26, otherNight: 17,
    name: 'Fearmonger',
    ability: 'Each night, choose a player. If you nominate & execute them, their team loses. All players know if you choose a new player.',
    reminders: [{ label: 'Fear', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'goblin', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: null,
    name: 'Goblin',
    ability: 'If you publicly claim to be the Goblin when nominated & are executed that day, your team wins.',
    reminders: [{ label: 'Claimed', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'harpy', team: 'minion', icon: 'swords',
    firstNight: 25, otherNight: 15,
    name: 'Harpy',
    ability: 'Each night, choose 2 players: tomorrow, the 1st player is mad that the 2nd is evil, or one or both might die.',
    reminders: [{ label: 'Mad', icon: 'circleDot', tone: 'evil' }, { label: '2nd', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'marionette', team: 'minion', icon: 'swords',
    firstNight: 12, otherNight: null, setup: true,
    name: 'Marionette',
    ability: 'You think you are a good character but you are not. The Demon knows who you are. [You neighbour the Demon]',
    reminders: [{ label: 'Is the Marionette', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'mezepheles', team: 'minion', icon: 'swords',
    firstNight: 27, otherNight: 18,
    name: 'Mezepheles',
    ability: 'You start knowing a secret word. The 1st good player to say this word becomes evil that night.',
    reminders: [{ label: 'Turns evil', icon: 'circleDot', tone: 'evil' }, { label: 'No ability', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'organ_grinder', team: 'minion', icon: 'swords',
    firstNight: 16, otherNight: 30,
    name: 'Organ Grinder',
    ability: 'All players keep their eyes closed when voting and the vote tally is secret. Each night, choose if you are drunk until dusk.',
    reminders: [{ label: 'Drunk', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'psychopath', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: null,
    name: 'Psychopath',
    ability: 'Each day, before nominations, you may publicly choose a player: they die. If executed, you only die if you lose roshambo.',
    reminders: [],
  },
  {
    id: 'summoner', team: 'minion', icon: 'swords',
    firstNight: 7, otherNight: 23, setup: true,
    name: 'Summoner',
    ability: 'You get 3 bluffs. On the 3rd night, choose a player: they become an evil Demon of your choice. [No Demon]',
    reminders: [{ label: 'Night 1', icon: 'circleDot', tone: 'evil' }, { label: 'Night 2', icon: 'circleDot', tone: 'evil' }, { label: 'Night 3', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'vizier', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: null,
    name: 'Vizier',
    ability: 'All players know you are the Vizier. You cannot die during the day. If good voted, you may choose to execute immediately.',
    reminders: [],
  },
  {
    id: 'widow', team: 'minion', icon: 'swords',
    firstNight: 18, otherNight: null,
    name: 'Widow',
    ability: 'On your 1st night, look at the Grimoire and choose a player: they are poisoned. 1 good player knows a Widow is in play.',
    reminders: [{ label: 'Poisoned', icon: 'circleDot', tone: 'evil' }, { label: 'Knows', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'wizard', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: null,
    name: 'Wizard',
    ability: 'Once per game, choose to make a wish. If granted, it might have a price and leave a clue as to its nature.',
    reminders: [{ label: 'Ability used', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'xaan', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: 7, setup: true,
    name: 'Xaan',
    ability: 'On night X, all Townsfolk are poisoned until dusk. [X Outsiders]',
    reminders: [{ label: 'Night 1', icon: 'circleDot', tone: 'evil' }, { label: 'Night 2', icon: 'circleDot', tone: 'evil' }, { label: 'Night 3', icon: 'circleDot', tone: 'evil' }, { label: 'X', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'acrobat', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: 39,
    name: 'Acrobat',
    ability: 'Each night*, if either good living neighbour is drunk or poisoned, you die.',
    reminders: [{ label: 'Dead', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'damsel', team: 'outsider', icon: 'userX',
    firstNight: 31, otherNight: 46,
    name: 'Damsel',
    ability: 'All Minions know you are in play. If a Minion publicly guesses you (once), your team loses.',
    reminders: [{ label: 'Guess used', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'golem', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Golem',
    ability: 'You may only nominate once per game. When you do, if the nominee is not the Demon, they die.',
    reminders: [{ label: 'Can not nominate', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'hatter', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: 40,
    name: 'Hatter',
    ability: 'If you died today or tonight, the Minion & Demon players may choose new Minion & Demon characters to be.',
    reminders: [{ label: 'Tea party tonight!', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'heretic', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Heretic',
    ability: 'Whoever wins, loses & whoever loses, wins, even if you are dead.',
    reminders: [],
  },
  {
    id: 'hermit', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null, setup: true,
    name: 'Hermit',
    ability: 'You have all Outsider abilities. [-0 or -1 Outsider]',
    reminders: [],
  },
  {
    id: 'ogre', team: 'outsider', icon: 'userX',
    firstNight: 40, otherNight: null,
    name: 'Ogre',
    ability: 'On your 1st night, choose a player (not yourself): you become their alignment (you don\'t know which) even if drunk or poisoned.',
    reminders: [],
  },
  {
    id: 'plague_doctor', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Plague Doctor',
    ability: 'When you die, the Storyteller gains a Minion ability.',
    reminders: [{ label: 'Storyteller ability', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'politician', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Politician',
    ability: 'If you were the player most responsible for your team losing, you change alignment & win, even if dead.',
    reminders: [],
  },
  {
    id: 'puzzlemaster', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Puzzlemaster',
    ability: '1 player is drunk, even if you die. If you guess (once) who it is, learn the Demon player, but guess wrong & get false info.',
    reminders: [{ label: 'Drunk', icon: 'circleDot', tone: 'good' }, { label: 'Guess used', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'snitch', team: 'outsider', icon: 'userX',
    firstNight: 7, otherNight: null,
    name: 'Snitch',
    ability: 'Minions start knowing 3 not-in-play characters.',
    reminders: [],
  },
  {
    id: 'zealot', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Zealot',
    ability: 'If there are 5 or more players alive, you must vote for every nomination.',
    reminders: [],
  },
  {
    id: 'alchemist', team: 'townsfolk', icon: 'user',
    firstNight: 3, otherNight: null,
    name: 'Alchemist',
    ability: 'You have a not-in-play Minion ability.',
    reminders: [{ label: 'Is the Alchemist', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'alsaahir', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Alsaahir',
    ability: 'Each day, if you publicly guess which players are Minion(s) and which are Demon(s), good wins.',
    reminders: [{ label: 'Incorrect Guess', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'amnesiac', team: 'townsfolk', icon: 'user',
    firstNight: 32, otherNight: 47,
    name: 'Amnesiac',
    ability: 'You do not know what your ability is. Each day, privately guess what it is: you learn how accurate you are.',
    reminders: [{ label: '?', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'atheist', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null, setup: true,
    name: 'Atheist',
    ability: 'The Storyteller can break the game rules & if executed, good wins, even if you are dead. [No evil characters]',
    reminders: [],
  },
  {
    id: 'balloonist', team: 'townsfolk', icon: 'user',
    firstNight: 45, otherNight: 62, setup: true,
    name: 'Balloonist',
    ability: 'Each night, you learn 1 player of each character type, until there are no more types to learn. [+1 Outsider]',
    reminders: [{ label: 'Seen Townsfolk', icon: 'circleDot', tone: 'good' }, { label: 'Seen Outsider', icon: 'circleDot', tone: 'good' }, { label: 'Seen Minion', icon: 'circleDot', tone: 'good' }, { label: 'Seen Demon', icon: 'circleDot', tone: 'good' }, { label: 'Seen Traveller', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'banshee', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Banshee',
    ability: 'If the Demon kills you, all players learn this. From now on, you may nominate twice per day and vote twice per nomination.',
    reminders: [{ label: 'Undead Banshee', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'bounty_hunter', team: 'townsfolk', icon: 'user',
    firstNight: 46, otherNight: 64, setup: true,
    name: 'Bounty Hunter',
    ability: 'You start knowing 1 evil player. If the player you know dies, you learn another evil player tonight. [1 Townsfolk is evil]',
    reminders: [{ label: 'Known', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'cannibal', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Cannibal',
    ability: 'You have the ability of the recently killed executee. If they are evil, you are poisoned until a good player dies by execution.',
    reminders: [{ label: 'Poisoned', icon: 'circleDot', tone: 'good' }, { label: 'Died today', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'choirboy', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 44, setup: true,
    name: 'Choirboy',
    ability: 'If the Demon kills the King, you learn which player is the Demon. [+ the King]',
    reminders: [],
  },
  {
    id: 'cult_leader', team: 'townsfolk', icon: 'user',
    firstNight: 48, otherNight: 66,
    name: 'Cult Leader',
    ability: 'Each night, you become the alignment of an alive neighbour. If all good players choose to join your cult, your team wins.',
    reminders: [],
  },
  {
    id: 'engineer', team: 'townsfolk', icon: 'user',
    firstNight: 13, otherNight: 5,
    name: 'Engineer',
    ability: 'Once per game, at night, choose which Minions or which Demon is in play.',
    reminders: [{ label: 'No ability', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'farmer', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 48,
    name: 'Farmer',
    ability: 'If you die at night, an alive good player becomes a Farmer.',
    reminders: [],
  },
  {
    id: 'fisherman', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Fisherman',
    ability: 'Once per game, during the day, visit the Storyteller for some advice to help you win.',
    reminders: [{ label: 'No ability', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'general', team: 'townsfolk', icon: 'user',
    firstNight: 50, otherNight: 69,
    name: 'General',
    ability: 'Each night, you learn which alignment the Storyteller believes is winning: good, evil, or neither.',
    reminders: [],
  },
  {
    id: 'high_priestess', team: 'townsfolk', icon: 'user',
    firstNight: 50, otherNight: 69,
    name: 'High Priestess',
    ability: 'Each night, learn which player the Storyteller believes you should talk to most.',
    reminders: [],
  },
  {
    id: 'huntsman', team: 'townsfolk', icon: 'user',
    firstNight: 30, otherNight: 45, setup: true,
    name: 'Huntsman',
    ability: 'Once per game, at night, choose a living player: the Damsel, if chosen, becomes a not-in-play Townsfolk. [+the Damsel]',
    reminders: [{ label: 'No ability', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'king', team: 'townsfolk', icon: 'user',
    firstNight: 10, otherNight: 63,
    name: 'King',
    ability: 'Each night, if the dead outnumber the living, you learn 1 alive character. The Demon knows who you are.',
    reminders: [],
  },
  {
    id: 'knight', team: 'townsfolk', icon: 'user',
    firstNight: 33, otherNight: null,
    name: 'Knight',
    ability: 'You start knowing 2 players that are not the Demon.',
    reminders: [{ label: 'Know', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'lycanthrope', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 22,
    name: 'Lycanthrope',
    ability: 'Each night*, choose a living player: if good, they die, but they are the only player that can die tonight.',
    reminders: [{ label: 'Dead', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'magician', team: 'townsfolk', icon: 'user',
    firstNight: 5, otherNight: null,
    name: 'Magician',
    ability: 'The Demon thinks you are a Minion. Minions think you are a Demon.',
    reminders: [],
  },
  {
    id: 'nightwatchman', team: 'townsfolk', icon: 'user',
    firstNight: 47, otherNight: 65,
    name: 'Nightwatchman',
    ability: 'Once per game, at night, choose a player: they learn who you are.',
    reminders: [{ label: 'No ability', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'noble', team: 'townsfolk', icon: 'user',
    firstNight: 44, otherNight: null,
    name: 'Noble',
    ability: 'You start knowing 3 players, 1 and only 1 of which is evil.',
    reminders: [{ label: 'Seen', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'pixie', team: 'townsfolk', icon: 'user',
    firstNight: 29, otherNight: null,
    name: 'Pixie',
    ability: 'You start knowing 1 in-play Townsfolk. If you were mad that you were this character, you gain their ability when they die.',
    reminders: [{ label: 'Mad', icon: 'circleDot', tone: 'good' }, { label: 'Has ability', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'poppy_grower', team: 'townsfolk', icon: 'user',
    firstNight: 4, otherNight: 3,
    name: 'Poppy Grower',
    ability: 'Minions & Demons do not know each other. If you die, they learn who each other are that night.',
    reminders: [{ label: 'Evil wakes', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'preacher', team: 'townsfolk', icon: 'user',
    firstNight: 14, otherNight: 6,
    name: 'Preacher',
    ability: 'Each night, choose a player: a Minion, if chosen, learns this. All chosen Minions have no ability.',
    reminders: [{ label: 'At a sermon', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'princess', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Princess',
    ability: 'On your 1st day, if you nominated & executed a player, the Demon doesn\'t kill tonight.',
    reminders: [{ label: 'Doesn\'t act', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'shugenja', team: 'townsfolk', icon: 'user',
    firstNight: 41, otherNight: null,
    name: 'Shugenja',
    ability: 'You start knowing if your closest evil player is clockwise or anti-clockwise. If equidistant, this info is arbitrary.',
    reminders: [],
  },
  {
    id: 'steward', team: 'townsfolk', icon: 'user',
    firstNight: 1, otherNight: null,
    name: 'Steward',
    ability: 'You start knowing 1 good player.',
    reminders: [{ label: 'Know', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'village_idiot', team: 'townsfolk', icon: 'user',
    firstNight: 38, otherNight: 54, setup: true,
    name: 'Village Idiot',
    ability: 'Each night, choose a player: you learn their alignment. [+0 to +2 Village Idiots. 1 of the extras is drunk]',
    reminders: [{ label: 'Drunk', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'apprentice', team: 'traveller', icon: 'user',
    firstNight: 1, otherNight: null,
    name: 'Apprentice',
    ability: 'On your 1st night, you gain a Townsfolk ability (if good), or a Minion ability (if evil).',
    reminders: [{ label: 'Is the Apprentice', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'barista', team: 'traveller', icon: 'user',
    firstNight: 1, otherNight: 1,
    name: 'Barista',
    ability: 'Each night, until dusk, 1) a player becomes sober, healthy and gets true info, or 2) their ability works twice. They learn which.',
    reminders: [{ label: 'Sober & Healthy', icon: 'circleDot', tone: 'good' }, { label: 'Ability twice', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'beggar', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Beggar',
    ability: 'You must use a vote token to vote. Dead players may choose to give you theirs. If so, you learn their alignment. You are sober & healthy.',
    reminders: [],
  },
  {
    id: 'bishop', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Bishop',
    ability: 'Only the Storyteller can nominate. At least 1 opposite player must be nominated each day.',
    reminders: [{ label: 'Nominate good', icon: 'circleDot', tone: 'good' }, { label: 'Nominate evil', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'bone_collector', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: 1,
    name: 'Bone Collector',
    ability: 'Once per game, at night, choose a dead player: they regain their ability until dusk.',
    reminders: [{ label: 'No ability', icon: 'circleDot', tone: 'good' }, { label: 'Has ability', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'bureaucrat', team: 'traveller', icon: 'user',
    firstNight: 1, otherNight: 1,
    name: 'Bureaucrat',
    ability: 'Each night, choose a player (not yourself): their vote counts as 3 votes tomorrow.',
    reminders: [{ label: '3 votes', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'butcher', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Butcher',
    ability: 'Each day, after the 1st execution, you may nominate again.',
    reminders: [],
  },
  {
    id: 'deviant', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Deviant',
    ability: 'If you were funny today, you cannot die by exile.',
    reminders: [],
  },
  {
    id: 'ferryman', team: 'fabled', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Ferryman',
    ability: 'On the final day, all dead players regain their vote token.',
    reminders: [],
  },
  {
    id: 'cacklejack', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Cacklejack',
    ability: 'Each day, choose a player: a different player changes character tonight.',
    reminders: [{ label: 'Not Me', icon: 'circleDot', tone: 'neutral' }],
  },
  {
    id: 'gangster', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Gangster',
    ability: 'Once per day, you may choose to kill an alive neighbour, if your other alive neighbour agrees.',
    reminders: [],
  },
  {
    id: 'gnome', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Gnome',
    ability: 'All players start knowing a player of your alignment. You may choose to kill anyone who nominates them.',
    reminders: [{ label: 'Amigo', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'gunslinger', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Gunslinger',
    ability: 'Each day, after the 1st vote has been tallied, you may choose a player that voted: they die.',
    reminders: [],
  },
  {
    id: 'harlot', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: 1,
    name: 'Harlot',
    ability: 'Each night*, choose a living player: if they agree, you learn their character, but you both might die.',
    reminders: [{ label: 'Dead', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'judge', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Judge',
    ability: 'Once per game, if another player nominated, you may choose to force the current execution to pass or fail.',
    reminders: [{ label: 'No ability', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'matron', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Matron',
    ability: 'Each day, you may choose up to 3 sets of 2 players to swap seats. Players may not leave their seats to talk in private.',
    reminders: [],
  },
  {
    id: 'scapegoat', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Scapegoat',
    ability: 'If a player of your alignment is executed, you might be executed instead.',
    reminders: [],
  },
  {
    id: 'thief', team: 'traveller', icon: 'user',
    firstNight: 1, otherNight: 1,
    name: 'Thief',
    ability: 'Each night, choose a player (not yourself): their vote counts negatively tomorrow.',
    reminders: [{ label: 'Negative vote', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'voudon', team: 'traveller', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Voudon',
    ability: 'Only you and the dead can vote. They don\'t need a vote token to do so. A 50% majority is not required.',
    reminders: [],
  },
  {
    id: 'wraith', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: null,
    name: 'Wraith',
    ability: 'You may choose to open your eyes at night. You wake when other evil players do.',
    reminders: [],
  },
]
