// AUTO-GENERATED from canonical BotC character data (bra1n/townsquare roles.json).
// Manual-board character data only (no night-action engine). Edit here directly;
// there is no live generator in the repo. See editions/types.ts for the shape.
import type { EditionRole } from './types'

export const SECTS_AND_VIOLETS: EditionRole[] = [
  {
    id: 'clockmaker', team: 'townsfolk', icon: 'user',
    firstNight: 41, otherNight: null,
    name: 'Clockmaker',
    ability: 'You start knowing how many steps from the Demon to its nearest Minion.',
    reminders: [],
  },
  {
    id: 'dreamer', team: 'townsfolk', icon: 'user',
    firstNight: 42, otherNight: 56,
    name: 'Dreamer',
    ability: 'Each night, choose a player (not yourself or Travellers): you learn 1 good and 1 evil character, 1 of which is correct.',
    reminders: [],
  },
  {
    id: 'snake_charmer', team: 'townsfolk', icon: 'user',
    firstNight: 20, otherNight: 11,
    name: 'Snake Charmer',
    ability: 'Each night, choose an alive player: a chosen Demon swaps characters & alignments with you & is then poisoned.',
    reminders: [{ label: 'Poisoned', icon: 'flask', tone: 'good' }],
  },
  {
    id: 'mathematician', team: 'townsfolk', icon: 'user',
    firstNight: 52, otherNight: 71,
    name: 'Mathematician',
    ability: 'Each night, you learn how many players’ abilities worked abnormally (since dawn) due to another character\'s ability.',
    reminders: [{ label: 'Abnormal', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'flowergirl', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 57,
    name: 'Flowergirl',
    ability: 'Each night*, you learn if a Demon voted today.',
    reminders: [{ label: 'Demon voted', icon: 'flame', tone: 'good' }, { label: 'Demon not voted', icon: 'flame', tone: 'good' }],
  },
  {
    id: 'town_crier', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 58,
    name: 'Town Crier',
    ability: 'Each night*, you learn if a Minion nominated today.',
    reminders: [{ label: 'Minions not nominated', icon: 'swords', tone: 'good' }, { label: 'Minion nominated', icon: 'swords', tone: 'good' }],
  },
  {
    id: 'oracle', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 59,
    name: 'Oracle',
    ability: 'Each night*, you learn how many dead players are evil.',
    reminders: [],
  },
  {
    id: 'savant', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Savant',
    ability: 'Each day, you may visit the Storyteller to learn 2 things in private: 1 is true & 1 is false.',
    reminders: [],
  },
  {
    id: 'seamstress', team: 'townsfolk', icon: 'user',
    firstNight: 43, otherNight: 60,
    name: 'Seamstress',
    ability: 'Once per game, at night, choose 2 players (not yourself): you learn if they are the same alignment.',
    reminders: [{ label: 'No ability', icon: 'zapOff', tone: 'good' }],
  },
  {
    id: 'philosopher', team: 'townsfolk', icon: 'user',
    firstNight: 2, otherNight: 2,
    name: 'Philosopher',
    ability: 'Once per game, at night, choose a good character: gain that ability. If this character is in play, they are drunk.',
    reminders: [{ label: 'Drunk', icon: 'beer', tone: 'good' }, { label: 'Is the Philosopher', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'artist', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: null,
    name: 'Artist',
    ability: 'Once per game, during the day, privately ask the Storyteller any yes/no question.',
    reminders: [{ label: 'No ability', icon: 'zapOff', tone: 'good' }],
  },
  {
    id: 'juggler', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 61,
    name: 'Juggler',
    ability: 'On your 1st day, publicly guess up to 5 players\' characters. That night, you learn how many you got correct.',
    reminders: [{ label: 'Correct', icon: 'circleDot', tone: 'good' }],
  },
  {
    id: 'sage', team: 'townsfolk', icon: 'user',
    firstNight: null, otherNight: 42,
    name: 'Sage',
    ability: 'If the Demon kills you, you learn that it is 1 of 2 players.',
    reminders: [],
  },
  {
    id: 'mutant', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Mutant',
    ability: 'If you are “mad” about being an Outsider, you might be executed.',
    reminders: [],
  },
  {
    id: 'sweetheart', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: 41,
    name: 'Sweetheart',
    ability: 'When you die, 1 player is drunk from now on.',
    reminders: [{ label: 'Drunk', icon: 'beer', tone: 'neutral' }],
  },
  {
    id: 'barber', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: 40,
    name: 'Barber',
    ability: 'If you died today or tonight, the Demon may choose 2 players (not another Demon) to swap characters.',
    reminders: [{ label: 'Haircuts tonight', icon: 'circleDot', tone: 'neutral' }],
  },
  {
    id: 'klutz', team: 'outsider', icon: 'userX',
    firstNight: null, otherNight: null,
    name: 'Klutz',
    ability: 'When you learn that you died, publicly choose 1 alive player: if they are evil, your team loses.',
    reminders: [],
  },
  {
    id: 'evil_twin', team: 'minion', icon: 'swords',
    firstNight: 23, otherNight: null,
    name: 'Evil Twin',
    ability: 'You & an opposing player know each other. If the good player is executed, evil wins. Good can\'t win if you both live.',
    reminders: [{ label: 'Twin', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'witch', team: 'minion', icon: 'swords',
    firstNight: 24, otherNight: 14,
    name: 'Witch',
    ability: 'Each night, choose a player: if they nominate tomorrow, they die. If just 3 players live, you lose this ability.',
    reminders: [{ label: 'Cursed', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'cerenovus', team: 'minion', icon: 'swords',
    firstNight: 25, otherNight: 15,
    name: 'Cerenovus',
    ability: 'Each night, choose a player & a good character: they are “mad” they are this character tomorrow, or might be executed.',
    reminders: [{ label: 'Mad', icon: 'flame', tone: 'evil' }],
  },
  {
    id: 'pit_hag', team: 'minion', icon: 'swords',
    firstNight: null, otherNight: 16,
    name: 'Pit-Hag',
    ability: 'Each night*, choose a player & a character they become (if not-in-play). If a Demon is made, deaths tonight are arbitrary.',
    reminders: [],
  },
  {
    id: 'fang_gu', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 29, setup: true,
    name: 'Fang Gu',
    ability: 'Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu & you die instead. [+1 Outsider]',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'evil' }, { label: 'Once', icon: 'circleDot', tone: 'evil' }],
  },
  {
    id: 'vigormortis', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 32, setup: true,
    name: 'Vigormortis',
    ability: 'Each night*, choose a player: they die. Minions you kill keep their ability & poison 1 Townsfolk neighbour. [−1 Outsider]',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'evil' }, { label: 'Has ability', icon: 'circleDot', tone: 'evil' }, { label: 'Poisoned', icon: 'flask', tone: 'evil' }],
  },
  {
    id: 'no_dashii', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 30,
    name: 'No Dashii',
    ability: 'Each night*, choose a player: they die. Your 2 Townsfolk neighbours are poisoned.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'evil' }, { label: 'Poisoned', icon: 'flask', tone: 'evil' }],
  },
  {
    id: 'vortox', team: 'demon', icon: 'flame',
    firstNight: null, otherNight: 31,
    name: 'Vortox',
    ability: 'Each night*, choose a player: they die. Townsfolk abilities yield false info. Each day, if no-one is executed, evil wins.',
    reminders: [{ label: 'Dead', icon: 'skull', tone: 'evil' }],
  },
]
