// AUTO-GENERATED. Full pre-composed reminder token PNGs live in
// public/assets/reminders/<key>.png, keyed `<roleNorm>__<labelNorm>` where each
// part is lowercased and stripped to [a-z0-9]. Regenerate by re-running the
// reminder image pipeline (see git history) when the art set changes.
const BASE = import.meta.env.BASE_URL

const KEYS = new Set<string>([
  "acrobat__chosen",
  "acrobat__dead",
  "alchemist__isthealchemist",
  "alhadikhia__1",
  "alhadikhia__2",
  "alhadikhia__3",
  "amnesiac__",
  "angel__protected",
  "angel__somethingbad",
  "apprentice__istheapprentice",
  "artist__noability",
  "assassin__dead",
  "assassin__noability",
  "balloonist__know",
  "balloonist__know2",
  "balloonist__know3",
  "balloonist__know4",
  "banshee__hasability",
  "barber__haircutstonight",
  "barista__",
  "barista__actstwice",
  "barista__soberhealthy",
  "bishop__nominateevil",
  "bishop__nominategood",
  "bonecollector__hasability",
  "bonecollector__noability",
  "bountyhunter__know",
  "bureaucrat__3votes",
  "butler__master",
  "cacklejack__notme",
  "cannibal__lunch",
  "cannibal__poisoned",
  "cerenovus__mad",
  "courtier__drunk1",
  "courtier__drunk2",
  "courtier__drunk3",
  "courtier__noability",
  "damsel__guessused",
  "deusexfiasco__whoopsie",
  "devilsadvocate__survivesexecution",
  "drunk__isthedrunk",
  "duchess__falseinfo",
  "duchess__visitor",
  "engineer__noability",
  "eviltwin__twin",
  "exorcist__chosen",
  "fanggu__dead",
  "fanggu__once",
  "fearmonger__fear",
  "fibbin__noability",
  "fisherman__noability",
  "flowergirl__demonnotvoted",
  "flowergirl__demonvoted",
  "fool__noability",
  "fortuneteller__redherring",
  "gambler__dead",
  "gnome__amigo",
  "goblin__claimed",
  "godfather__dead",
  "godfather__diedtoday",
  "golem__maynotnominate",
  "goon__drunk",
  "gossip__dead",
  "grandmother__dead",
  "grandmother__grandchild",
  "harlot__dead",
  "harpy__2nd",
  "harpy__mad",
  "hatter__teapartytonight",
  "hellslibrarian__somethingbad",
  "hermit__1",
  "hermit__2",
  "hermit__3",
  "huntsman__noability",
  "imp__dead",
  "innkeeper__drunk",
  "innkeeper__safe",
  "investigator__minion",
  "investigator__wrong",
  "judge__noability",
  "juggler__correct",
  "kazali__dead",
  "knight__know",
  "knight__know2",
  "legion__abouttodie",
  "legion__dead",
  "leviathan__day1",
  "leviathan__day2",
  "leviathan__day3",
  "leviathan__day4",
  "leviathan__day5",
  "leviathan__goodplayerexecuted",
  "librarian__outsider",
  "librarian__wrong",
  "lilmonsta__dead",
  "lilmonsta__isthedemon",
  "lleech__dead",
  "lleech__poisoned",
  "lordoftyphon__dead",
  "lunatic__chosen",
  "lycanthrope__dead",
  "lycanthrope__fauxpaw",
  "marionette__isthemarionette",
  "mathematician__abnormal",
  "mezepheles__noability",
  "mezepheles__turnsevil",
  "minstrel__everyoneisdrunk",
  "monk__safe",
  "moonchild__dead",
  "nightwatchman__noability",
  "noble__know",
  "nodashii__dead",
  "nodashii__poisoned",
  "ogre__friend",
  "ojo__dead",
  "organgrinder__abouttodie",
  "organgrinder__drunk",
  "philosopher__drunk",
  "philosopher__isthephilosopher",
  "pixie__hasability",
  "pixie__mad",
  "plaguedoctor__storytellerability",
  "po__3attacks",
  "po__dead",
  "poisoner__poisoned",
  "poppygrower__evilwakes",
  "preacher__noability",
  "princess__doesntact",
  "professor__alive",
  "professor__noability",
  "pukka__dead",
  "pukka__poisoned",
  "puzzlemaster__drunk",
  "puzzlemaster__guessused",
  "revolutionary__registerfalsely",
  "riot__day1",
  "riot__day2",
  "riot__day3",
  "sailor__drunk",
  "scarletwoman__isthedemon",
  "seamstress__noability",
  "shabaloth__alive",
  "shabaloth__dead",
  "slayer__noability",
  "snakecharmer__poisoned",
  "spiritofivory__nomoreevil",
  "steward__know",
  "stormcatcher__safe",
  "summoner__night1",
  "summoner__night2",
  "summoner__night3",
  "sweetheart__drunk",
  "tealady__cannotdie",
  "thief__negativevote",
  "tinker__dead",
  "towncrier__minionnominated",
  "towncrier__minionnotnominated",
  "toymaker__finalnightnoattack",
  "undertaker__diedtoday",
  "vigormortis__dead",
  "vigormortis__hasability",
  "vigormortis__poisoned",
  "villageidiot__drunk",
  "virgin__noability",
  "vortox__dead",
  "washerwoman__townsfolk",
  "washerwoman__wrong",
  "widow__know",
  "widow__poisoned",
  "witch__cursed",
  "wizard__",
  "xaan__night1",
  "xaan__night2",
  "xaan__night3",
  "xaan__x",
  "yaggababble__dead",
  "zombuul__dead",
  "zombuul__diedtoday",
])

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '')

// App labels that read differently from the official token wording. Maps our
// key -> the art file key so these still resolve real art.
const ALIASES: Record<string, string> = {
  towncrier__minionsnotnominated: 'towncrier__minionnotnominated',
  minstrel__everyonedrunk: 'minstrel__everyoneisdrunk',
  innkeeper__protected: 'innkeeper__safe',
}

/**
 * Resolve the full reminder-token art URL for a role + reminder label, or
 * undefined when no official token image exists (caller falls back to the
 * styled pip). Role id separators are dropped to match the art file keys.
 */
export function getReminderTokenArt(roleId: string, label: string): string | undefined {
  const raw = norm(roleId) + '__' + norm(label)
  const key = ALIASES[raw] ?? raw
  return KEYS.has(key) ? `${BASE}assets/reminders/${key}.png` : undefined
}
